urlshortener/urlmgmt/urls.py

from django.urls import path
from django.conf.urls import url
from . import views
from . import services

app_name = 'urlmgmt'
urlpatterns = [
    # for our home/index page
    url(r'^index/', views.index, name='index'),

    # when short URL is requested it redirects to original URL
    # path(r'^(?P&lt;short_id&gt;\w{6})$', views.redirect_original, name='redirectoriginal'),
    # this will create a URL's short id and return the short URL
    url(r'^makeshort/', views.shorten_url, name='makeshort'),
    
    # APIs
    url(r'^api/v1/urls/', services.ShortUrlAPIView.as_view(), name='classview'),

    # url(r'^(?P<short_url>w{6})$', views.redirect_url, name='redirect'),
    url(r'^(?P<url>.+)/$', views.redirect_url, name='redirect'),
]



urlshortener/urlshortener/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from urlmgmt import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('urlmgmt.urls')),
    # url(r'^(?P<short_url>w{6})$', views.redirect_url, name='redirect'),
]

urlshortener/urlmgmt/models.py
from django.utils import timezone
from django.db import models
from django.conf import settings


class URL(models.Model):
    short_url = models.URLField(max_length=50, primary_key=True)
    http_url = models.URLField(unique=True)
    visitor_count = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.http_url

urlshortener/urlmgmt/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .models import URL
from . import services
import shortuuid
from django.conf import settings


def index(request):
    context = {}
    return render(request, 'urlmgmt/index.html', context)


def shorten_url(request):
    url = request.POST.get("httpurl", '')
    context = {}
    if not (url == ''):
        try:
            url_object = URL.objects.filter(http_url=url)
            if url_object:
                url_object = URL.objects.get(http_url=url)
                print("Existing URL object found", url_object.created, type(url_object.created))
                if services.is_valid_url(url_object.created):
                    print("URL object not expired")
                    pass
                else:
                    print("Object is expired, extending expiry time")
                    import datetime
                    url_object.created = datetime.datetime.now()
                    url_object.save()
            else:
                print("Create new URL object")
                url_object = URL.objects.create(
                    short_url=settings.SITE_URL + "/" + shortuuid.ShortUUID().random(length=6),
                    http_url=url
                )

            context['short_url'] = url_object.short_url
            context['http_url'] = url_object.http_url
            print("context:", context)

        except Exception as ex:
            context['error'] = ex
    else:
        context['error'] = "URL input is not supplied"
    return render(request, 'urlmgmt/index.html', context)


def redirect_url(request, url=None):
    try:
        print("url : ", url)
        short_url = settings.SITE_URL + "/" + url
        print("Short url : ", short_url)
        url_object = URL.objects.get(short_url=short_url)
        print("http url:", url_object.http_url)

    except Exception as e:
        context = {'error': e}
        return render(request, 'urlmgmt/index.html', context)

    if services.is_valid_url(url_object.created):

        url_object.visitor_count += 1
        url_object.save()
        return redirect(url_object.http_url)
    else:
        context = {'error': 'Short URL does not valid'}
        return render(request, 'urlmgmt/index.html', context)

urlshortener/urlmgmt/templates/urlmgmt/base.html
<!-- This is for future enhancement -->

urlshortener/urlmgmt/templates/urlmgmt/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Short Links</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<script type="text/javascript"> window.CSRF_TOKEN = "{{ csrf_token }}"; </script>
  <script type="text/javascript">
   $(function() {
      $("#shorten").click(function () {
        var url = $("#httpurl").val();
        $.ajax({
          url: '/api/v1/urls/',
          type : "POST",
          data: {
            'url': url,
             'csrfmiddlewaretoken': window.CSRF_TOKEN
          },
          dataType: 'json',
          success: function (data) {
            if (data) {
              document.getElementById('green').style.display="block";
              document.getElementById("urlid").href = data['http_url'];
              document.getElementById("urlid").innerHTML = data['short_url'];
            }
            else{
              var red = document.getElementById('red').style.display="block";
            }
          },
          error : function(xhr,errmsg,err) {
            document.getElementById('red').style.display="block";
            document.getElementById("error").innerHTML = err
          }
        });
      });
   });
  </script>


</head>
<body>

<div class="container">
  <h2>Create short links </h2>
  <hr>
  <form action="{% url 'urlmgmt:makeshort' %}" method="post">
     {% csrf_token %}
    <div class="form-group">
      <label for="httpurl">Enter URL </label>
      <input class="form-control" id="httpurl" type="text" placeholder="Shorten your link - http://www.facebook.com" name="httpurl" required>
    </div>
     <button type="button"  class="btn btn-primary" id="shorten">Shorten</button>
  </form>

  <br>


  <div class="alert alert-success green" id="green" style="display:none">
    <strong>Shorten URL: </strong> <a target="_blank" href="" id="urlid"> </a>
  </div>


  <div class="alert alert-danger red" id="red" style="display:none">
    <strong>Error:</strong> <p id="error"> </p>
  </div>

</div>
</body>
</html>